development:
  password: shptka_e572e32dd830f3ed1a1c24bfaaf2f2ca
  theme_id: 125528768709
  store: biktrix-ca.myshopify.com

# Windows	%APPDATA%\Shopify\Themekit\variables
# Linux/BSDs	${XDG_CONFIG_HOME}/Shopify/Themekit/variables
# MacOSX	${HOME}/Library/Application Support/Shopify/Themekit/variables
# Any	--vars flag provides a path to a file for loading variables
# file to load ignore patterns, check out the ignore file example